const SUCCESS = 201;
const REDIRECT = 300;
const CLIENT_ERROR = 401;
const INFO_EMPTY_ERROR = 402;
const SERVER_ERROR = 500;

const DEFAULT_SUCCESS_MESSAGE = 'ok';
module.exports = {
  SUCCESS,
  REDIRECT,
  INFO_EMPTY_ERROR,
  CLIENT_ERROR,
  SERVER_ERROR,
  DEFAULT_SUCCESS_MESSAGE,
};
