const SUCCESS = 201;
const REDIRECT = 300;
const CLIENT_ERROR = 403;
const SERVER_ERROR = 500;

const DEFAULT_SUCCESS_MESSAGE = 'ok'
module.exports = { SUCCESS, REDIRECT, CLIENT_ERROR, SERVER_ERROR, DEFAULT_SUCCESS_MESSAGE };
