const SUCCESS = 201;
const REDIRECT = 300;
const USER_ERROR = 401;
const CLIENT_ERROR = 403;
const PAGE_ERROR = 404;
const SERVER_ERROR = 500;

const DEFAULT_SUCCESS_MESSAGE = 'ok';
module.exports = { SUCCESS, REDIRECT, USER_ERROR, CLIENT_ERROR, PAGE_ERROR, SERVER_ERROR, DEFAULT_SUCCESS_MESSAGE };
